---
title: "Assignment 1: Introduction"
author: "Aadya Shukla"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.

7.  Initial here to acknowledge that you did not use AI at all in completing this assignment: AS

---

## 1) Concept and Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I briefly used R for an introductory statistics course in my Bachelor's - simple tasks such as plotting and making statistical inferences. I have never used Git before or any other analytical software.

2. Are there any components of the course about which you feel confident?

> Answer: I think I'm confident in my ability to grasp concepts quickly. I also feel confident knowing that there is a strong support system in the classroom among peers and especially from the instructor. On a technical level, however, it feels as if I have forgotten most of what I learned in my Bachelor's so this all feels new.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am worried about how the course load might be towards the second half of the semester, but that is just a minor concern.

4. Describe a dataset you have used in the past. Explain whether it was a primary or secondary dataset. 

> Answer: During a marine mammal internship, I assisted the team in collecting photographs of spinner dolphins and any associated metadata, such as population size, behavioral information, etc. We compiled and used this data for our own population demographic studies. I believe that this was a primary dataset since we collected the data ourselves.

5. Would you describe the day of the month as a nominal, ordinal, interval, or ratio number? Explain your reasoning.

> Answer: I think I would describe it as an interval number. The days follow an order with the same intervals between them but one number isn't any better than another, so it cannot be ordinal, or comparable to another, so it cannot be ratio.

---

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 

---

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
